name: meta_weather_api
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  http: ^0.13.0
  json_annotation: ^4.0.0

dev_dependencies:
  coverage: ^1.0.3
  build_runner: ^1.10.0
  json_serializable: ^4.0.0
  mocktail: ^0.2.0
  test: ^1.16.4